# When a micro servoce is used to register itself to the resgistry server  and fetch info about other services
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
